GameStoreApp/Controllers/CarrinhoCompraController.cs
using System.Linq;
using GameStoreApp.Models;
using GameStoreApp.Repositories;
using GameStoreApp.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace GameStoreApp.Controllers
{
    public class CarrinhoCompraController : Controller
    {
        private readonly IJogoRepository _jogoRepository;
        private readonly CarrinhoCompra _carrinhoCompra;

        public CarrinhoCompraController(IJogoRepository jogoRepository,
                                        CarrinhoCompra carrinhoCompra)
        {
            _jogoRepository = jogoRepository;
            _carrinhoCompra = carrinhoCompra;
        }
        public IActionResult Index()
        {
            var itens = _carrinhoCompra.GetCarrinhoCompraItens();
            _carrinhoCompra.CarrinhoCompraItens = itens;

            var carrinhoCompraVM = new CarrinhoCompraViewModel
            {
                CarrinhoCompra = _carrinhoCompra,
                CarrinhoCompraTotal = _carrinhoCompra.GetCarrinhoCompraTotal()
            };

            return View(carrinhoCompraVM);
        }

        [Authorize(Roles = "Admin, Member")]
        public RedirectToActionResult AdicionarItemNoCarrinhoCompra(int jogoId)
        {
            var jogoSelecionado = _jogoRepository.Jogos.FirstOrDefault(p => p.JogoId == jogoId);

            if (jogoSelecionado != null)
            {
                _carrinhoCompra.AdicionarAoCarrinho(jogoSelecionado, 1);
            }
            return RedirectToAction("Index");
        }

        [Authorize(Roles = "Admin, Member")]
        public IActionResult RemoverItemDoCarrinhoCompra(int jogoId)
        {
            var jogoSelecionado = _jogoRepository.Jogos.FirstOrDefault(p => p.JogoId == jogoId);
            if (jogoSelecionado != null)
            {
                _carrinhoCompra.RemoverDoCarrinho(jogoSelecionado);
            }
            return RedirectToAction("Index");
        }
    }
}

GameStoreApp/Controllers/ContatoController.cs
using Microsoft.AspNetCore.Mvc;

namespace GameStoreApp.Controllers
{
    public class ContatoController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

GameStoreApp/Views/Shared/_Carousel.cshtml
<div id="carouselJogos" class="carousel slide marginTop1" data-ride="carousel">
    <ol class="carousel-indicators">
        <li data-target="#carouselJogos" data-slide-to="0" class="active"></li>
        <li data-target="#carouselJogos" data-slide-to="1"></li>
        <li data-target="#carouselJogos" data-slide-to="2"></li>
        <li data-target="#carouselJogos" data-slide-to="3"></li>
    </ol>
    <div class="carousel-inner">
        <div class="carousel-item active">
            <img src="~/images/carousel01.jpeg" class="d-block w-100" alt="Jogo">
        </div>
        <div class="carousel-item">
            <img src="~/images/carousel02.jpg" class="d-block w-100" alt="Jogo">
        </div>
        <div class="carousel-item">
            <img src="~/images/carousel03.jpg" class="d-block w-100" alt="Jogo">
        </div>
        <div class="carousel-item">
            <img src="~/images/carousel04.jpg" class="d-block w-100" alt="Jogo">
        </div>
    </div>
    <a class="left carousel-control" href="#carouselJogos" data-slide="prev">
        <span class="glyphicon glyphicon-chevron-left"></span>
    </a>
    <a class="right carousel-control" href="#carouselJogos" data-slide="next">
        <span class="glyphicon glyphicon-chevron-right"></span>
    </a>
</div>
  

GameStoreApp/Views/Shared/_JogosResumo.cshtml
 @model Jogo           
            
<style>
                
#disabled {
    pointer-events: none;
    color: #ccc;
}
</style>
            
            <div class="col-sm-4 col-lg-4 col-md-4">
                <div class="thumbnail">
                    <img src="@Model.ImagemUrl" class="img-rounded" alt="" width="200" height="240">
                </div>
            <div class="caption">
                <h4 class="pull-right">@Model.Preco.ToString("c")</h4>
                <h3>
                    <a asp-controller="Jogo" asp-action="Details" asp-route-jogoId="@Model.JogoId">@Model.Nome</a>
                </h3>
                <p>@Model.DescricaoCurta</p>
            </div>
             <div text-right">
                <p class="formPullRightButton">

                    @if (@Model.EmEstoque == false)
                    {
                    <a id="disabled" class="btn btn-danger" asp-controller="CarrinhoCompra" asp-action="AdicionarItemNoCarrinhoCompra" asp-route-jogoId="@Model.JogoId">
                        Produto esgotado
                    </a>

                    }
                    else{
                    <a class="btn btn-primary" asp-controller="CarrinhoCompra" asp-action="AdicionarItemNoCarrinhoCompra" asp-route-jogoId="@Model.JogoId">
                        Adicionar ao Carrinho
                    </a>
                    }

                </p>
            </div>
            </div>

GameStoreApp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - GameStore </title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
@* <body style="background-color:#0164"> *@
    <body>
    <header>
        <nav class="navbar fixed-top navbar-expand-sm navbar-toggleable-sm navbar-dark bg-dark border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">GameStore</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    @await Html.PartialAsync("_LoginPartial")
                    <form class="form-inline my-2 my-lg-0" asp-controller="Jogo" asp-action="Search" method="get">
                        <div class="form-group">
                            <input class="form-control mr-sm-2" type="text" class="form-control" placeholder="Procurar jogo" name="searchString" value="@ViewData["searchString"]">
                        </div>
                    </form>
                    
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-white" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                      @await Component.InvokeAsync("CategoriaMenu");
                        <li class="nav-item">
                            <a class="nav-link text-white" asp-area="" asp-controller="Contato" asp-action="Index">Contato</a>
                        </li>
                        
                        @if (User.IsInRole("Admin"))
                        {
                            <li class="nav-item">
                                <a class="nav-link text-white" asp-area="Admin" asp-controller="Admin" asp-action="Index">Área de Administração</a>
                            </li>
                        }
                        @if (User.Identity.IsAuthenticated)
                        {
                        @await Component.InvokeAsync("CarrinhoCompraResumo")
                        }
                    </ul>
                        

                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - GameStoreApp - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>