GameStoreApp/Models/Jogo.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace GameStoreApp.Models
{
    public class Jogo
    {
        public int JogoId { get; set; }
        [Required]
        [StringLength(100)]
        public string Nome { get; set; }
        [StringLength(100)]
        public string DescricaoCurta { get; set; }
        [StringLength(255)]
        public string DescricaoDetalhada { get; set; }

        [Column(TypeName = "decimal(18,2)")]
        public decimal Preco { get; set; }
        [StringLength(200)]
        public string ImagemUrl { get; set; }

        [StringLength(200)]
        public string ImagemThumbnailUrl { get; set; }
        public bool isJogoPreferido { get; set; }
        public bool EmEstoque { get; set; }
        public int CategoriaId { get; set; }
        public virtual Categoria Categoria { get; set; }
    }
}

GameStoreApp/Controllers/CarrinhoCompraController.cs
using System.Linq;
using GameStoreApp.Models;
using GameStoreApp.Repositories;
using GameStoreApp.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace GameStoreApp.Controllers
{
    public class CarrinhoCompraController : Controller
    {
        private readonly IJogoRepository _jogoRepository;
        private readonly CarrinhoCompra _carrinhoCompra;

        public CarrinhoCompraController(IJogoRepository jogoRepository,
                                        CarrinhoCompra carrinhoCompra)
        {
            _jogoRepository = jogoRepository;
            _carrinhoCompra = carrinhoCompra;
        }
        public IActionResult Index()
        {
            var itens = _carrinhoCompra.GetCarrinhoCompraItens();
            _carrinhoCompra.CarrinhoCompraItens = itens;

            var carrinhoCompraVM = new CarrinhoCompraViewModel
            {
                CarrinhoCompra = _carrinhoCompra,
                CarrinhoCompraTotal = _carrinhoCompra.GetCarrinhoCompraTotal()
            };

            return View(carrinhoCompraVM);
        }

        [Authorize(Roles = "Admin, Member")]
        public RedirectToActionResult AdicionarItemNoCarrinhoCompra(int jogoId)
        {
            var jogoSelecionado = _jogoRepository.Jogos.FirstOrDefault(p => p.JogoId == jogoId);

            if (jogoSelecionado != null)
            {
                _carrinhoCompra.AdicionarAoCarrinho(jogoSelecionado, 1);
            }
            return RedirectToAction("Index");
        }

        [Authorize(Roles = "Admin, Member")]
        public IActionResult RemoverItemDoCarrinhoCompra(int jogoId)
        {
            var jogoSelecionado = _jogoRepository.Jogos.FirstOrDefault(p => p.JogoId == jogoId);
            if (jogoSelecionado != null)
            {
                _carrinhoCompra.RemoverDoCarrinho(jogoSelecionado);
            }
            return RedirectToAction("Index");
        }
    }
}

GameStoreApp/Controllers/JogoController.cs
using System.Collections.Generic;
using System.Linq;
using GameStoreApp.Models;
using GameStoreApp.Repositories;
using GameStoreApp.ViewModels;
using Microsoft.AspNetCore.Mvc;

namespace GameStoreApp.Controllers
{
    public class JogoController : Controller
    {
        private readonly IJogoRepository _jogoRepository;
        private ICategoriaRepository _categoriaRepository;

        public JogoController(IJogoRepository jogoRepository, ICategoriaRepository categoriaRepository)
        {
            _jogoRepository = jogoRepository;
            _categoriaRepository = categoriaRepository;
        }

        public IActionResult List(string categoria)
        {
            string _categoria = categoria;
            IEnumerable<Jogo> jogos;
            string categoriaAtual = string.Empty;

            if (string.IsNullOrEmpty(categoria))
            {
                jogos = _jogoRepository.Jogos.OrderBy(p => p.JogoId);
                categoriaAtual = "Todos os Jogos";
            }
            else
            {

                jogos = _jogoRepository.Jogos
                           .Where(p => p.Categoria.CategoriaNome.Equals(categoria))
                           .OrderBy(p => p.Nome);

                categoriaAtual = categoria;
            }

            var jogoListViewModel = new JogoListViewModel
            {
                Jogos = jogos,
                CategoriaAtual = categoriaAtual
            };

            return View(jogoListViewModel);

        }

        public IActionResult Details(int jogoId)
        {
            var jogo = _jogoRepository.Jogos.FirstOrDefault(j => j.JogoId == jogoId);
            if(jogo ==null)
            {
                return BadRequest("Not Found");
            }

            return View(jogo);
        }

        public ViewResult Search(string searchString)
        {
            string _searchString = searchString;
            IEnumerable<Jogo> jogos;
            string currentCategory = string.Empty;

            if (string.IsNullOrEmpty(_searchString))
            {
                jogos = _jogoRepository.Jogos.OrderBy(p => p.JogoId);
            }
            else
            {
                jogos = _jogoRepository.Jogos.Where(p => p.Nome.ToLower().Contains(_searchString.ToLower()));
            }

            return View("~/Views/Jogo/List.cshtml", new JogoListViewModel { Jogos = jogos, CategoriaAtual = "Todos os jogos"});
        }
    }
}

GameStoreApp/Views/Jogo/Details.cshtml
@model Jogo

<br/>
<br/>
<br/>
<style>              
#disabled {
    pointer-events: none;
    color: #ccc;
}
</style>

<div class="container marginTop">
    <div class="row">
        <div class="card border-0">
            <div class="text-center view overlay hm-white-slight">
                <img src="@Model.ImagemUrl" class="img-fluid" width="250" height="300">
                <a href="#">
                    <div class="mask waves-effect waves-light"></div>
                </a>
            </div>
            <div class="card-block">
                <!--Title-->
                <h2 class="card-title">@Model.Nome</h2>
                <!--Text-->
                <p class="card-text"><h5>@Model.DescricaoDetalhada</h5></p>
                <p class="btn btn-group align-content-lg-end" >
                    <a style="margin: 0 15px;" asp-controller="Jogo" asp-action="List" class="btn btn-secondary">Voltar para a lista de jogos</a>

                    @if (@Model.EmEstoque == false)
                    {
                    <a id="disabled" style="margin: 0 15px;" class="btn btn-danger" id="cartButton" asp-controller="CarrinhoCompra" asp-action="AdicionarItemNoCarrinhoCompra" asp-route-jogoId="@Model.JogoId">
                        Este produto está esgotado
                    </a>
                    }
                    else 
                    {
                    <a style="margin: 0 15px;" class="btn btn-primary" id="cartButton" asp-controller="CarrinhoCompra" asp-action="AdicionarItemNoCarrinhoCompra" asp-route-jogoId="@Model.JogoId">
                        Adicionar @Model.Nome ao carrinho
                    </a>
                    }
                </p>
            </div>
        </div>
    </div>
</div>

GameStoreApp/Views/Jogo/List.cshtml
@model JogoListViewModel
<br/>
<br/>
<br/>
    <div><h2>@Model.CategoriaAtual</h2></div>

    <div class="row">
        
        @foreach (Jogo jogo in Model.Jogos)
        {
            @* @Html.Partial("_JogosResumo", jogo) *@
            <partial name="_JogosResumo" for="@jogo"/>
        }
        
    </div>